[project]
name = "cluster_wrapper"
version = "0.1"
dependencies = [
    "htcondor",
    "paramiko",
    "pydantic",
    "pyyaml",
    "structlog",
]

[project.scripts]
prep-cluster-job = "job_prep:main"
htcluster-server = "job_exec.server:main"

[tool.isort]
profile = "black"

[tool.pyright]
venvPath = "/home/lkirk/repo/cluster-wrapper"
venv = "ve"
