[project]
name = "htcluster"
version = "0.1"
dependencies = [
    "pydantic",
    "structlog",
]

[project.optional-dependencies]
job_submit = [
    "numpy",
    "paramiko",
    "python-dateutil",
    "pyyaml",
    "pyzmq",
    "requests",
]
job_exec = [
    "htcondor",
    "python-dateutil",
    "pyzmq",
]
dev = ["ipython"]

[project.scripts]
htcluster-submit = "job_submit:main"
htcluster-server = "job_exec.server:main"
htcluster-wrapper = "job_wrapper:main"

[tool.isort]
profile = "black"

[tool.pyright]
venvPath = "."
venv = "ve"
