#!/bin/bash

set -eo pipefail

[[ -d ~/.venv/htcluster ]] && {
    echo removing existing env at ~/.venv/htcluster
    rm -r ~/.venv/htcluster
}
python -m venv ~/.venv/htcluster
source ~/.venv/htcluster/bin/activate
pip install -U pip setuptools
pip install ~/repo/htcluster/'.[job_exec]'
